version: '3.3'
services:
  station:
    image: rafiaaons/stationsky:1.0
    restart: always
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/stationSki?useUnicode=true&createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=
    ports:
      - "8089:8089"
    depends_on:
      - mysql
  mysql_db:
    image: "mysql:5.7.24"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: stationSki
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
 
  
